# SIMGRID prebuild Docker image.
# Author: O. Dalle
#
# Description:
# An compile-ready image with all required dependencies to build SG


FROM ubuntu:14.04

RUN export DISPLAY=:0.0 && \
    apt-get update && apt-get install -y \
    gcc-4.8 \
    g++-4.8 \
    g++ \
    cmake \
    git \
    libboost-context-dev \
    libboost-dev \
    openjdk-7-jdk \
    doxygen \
    transfig
    
